services:
  django:
    build: .
    container_name: django_app
    restart: always
    env_file: .env # Load environment variables
    depends_on:
      - db
    networks:
      - app_network
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: "mydatabase"
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres_data:
