"""
Django settings for my_cardio project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# import environ
from pathlib import Path
from cryptography.fernet import Fernet

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Trust requests from this domain
CSRF_TRUSTED_ORIGINS = ['https://skibidi.jhomelabs.co', 'https://mycardio.jhomelabs.co']

# Ensure CSRF cookie is only sent over HTTPS
CSRF_COOKIE_SECURE = True

# Allow CSRF cookie to be sent with cross-origin requests
CSRF_COOKIE_SAMESITE = 'None'

ALLOWED_HOSTS = ['192.168.18.100', 'localhost', '127.0.0.1', 'skibidi.jhomelabs.co', 'mycardio.jhomelabs.co','medirisk.jhomelabs.co']

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'my_cardio/static')]

# This is needed for `collectstatic` in production
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles") 

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_!5^e88nese-b3f&xpiwmnd58tr!c8$+f7wyfd!xo&$p1b0%+a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'channels'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_cardio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_cardio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',  # Use PostgreSQL backend
        'NAME': 'mydatabase',  # Database name (must match POSTGRES_DB in compose.yaml)
        'USER': 'myuser',  # Database user (must match POSTGRES_USER in compose.yaml)
        'PASSWORD': 'mypassword',  # Database password (must match POSTGRES_PASSWORD in compose.yaml)
        'HOST': 'db',  # Use the service name from compose.yaml
        'PORT': '5432',  # Default PostgreSQL port
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = "/home/"
LOGIN_URL = "/login/"
LOGOUT_REDIRECT_URL = "/"

AUTH_USER_MODEL = "main.CustomUser"  # Change 'main' if your app name is different

import os

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATIC_URL = "/static/"




FERNET_SECRET_KEY = os.getenv("FERNET_SECRET_KEY")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

INSTALLED_APPS += []
ASGI_APPLICATION = "myproject.asgi.application"


EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# AUTH_PASSWORD_VALIDATORS = []  # Disable temporarily for testing

DEBUG = True 