# Generated by Django 5.1.7 on 2025-04-02 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskassessmentresult',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='active',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='alco',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='chestpain',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='exerciseangia',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='maxheartrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='restingrelectro',
            field=models.IntegerField(blank=True, choices=[(0, 'Normal'), (1, 'ST-T wave abnormality'), (2, 'Left ventricular hypertrophy')], null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='smoke',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True),
        ),
        migrations.AddField(
            model_name='riskassessmentresult',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TermsAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
