# Generated by Django 5.1.7 on 2025-04-03 07:56

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_riskassessmentresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=main.models.user_profile_path),
        ),
    ]
