# Generated by Django 5.1.7 on 2025-03-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userprofile_profile_picture'),
        ('main', '0003_riskassessmentresult_recommendations'),
    ]

    operations = [
    ]
