# Generated by Django 5.1.7 on 2025-03-14 01:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(help_text='e.g., 130/90', max_length=20)),
                ('sugar_level', models.CharField(help_text='e.g., 110 mg/dL', max_length=20)),
                ('heart_rate', models.IntegerField(help_text='e.g., 75 bpm')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
