# Generated by Django 5.1.7 on 2025-03-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_appointment_consultation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessmentresult',
            name='bmi',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
