# Generated by Django 5.1.7 on 2025-03-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_riskassessmentresult_bmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessmentresult',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
