# Generated by Django 5.1.7 on 2025-03-14 03:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_riskassessmentresult_bmi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreport',
            name='assessment_date',
        ),
        migrations.RemoveField(
            model_name='healthreport',
            name='heart_rate',
        ),
        migrations.RemoveField(
            model_name='healthreport',
            name='sugar_level',
        ),
        migrations.AddField(
            model_name='healthreport',
            name='bmi',
            field=models.FloatField(default=25),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='cholesterol_level',
            field=models.FloatField(default=180),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='glucose_level',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='recommendations',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='healthreport',
            name='risk_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default=str, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthreport',
            name='risk_probability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='blood_pressure',
            field=models.IntegerField(default=0),
        ),
    ]
