# Generated by Django 5.1.7 on 2025-03-14 15:19

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_healthreport_assessment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthhistory',
            name='diagnosis',
            field=main.models.EncryptedCharField(help_text='Health risk assessment result', max_length=255),
        ),
        migrations.AlterField(
            model_name='healthhistory',
            name='recommendations',
            field=main.models.EncryptedTextField(blank=True, help_text='Suggested preventive actions'),
        ),
        migrations.AlterField(
            model_name='healthhistory',
            name='risk_score',
            field=main.models.EncryptedDecimalField(decimal_places=2, help_text='AI-generated risk score', max_digits=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=main.models.EncryptedFieldMixin(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=main.models.EncryptedFieldMixin(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=main.models.EncryptedFieldMixin(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='DataAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('data_type', models.CharField(max_length=255)),
                ('object_id', models.IntegerField()),
                ('action', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
