# Generated by Django 5.1.7 on 2025-03-14 15:25

import main.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_healthhistory_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=main.models.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=main.models.EncryptedCharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=main.models.EncryptedCharField(blank=True, max_length=15, null=True),
        ),
    ]
