# Generated by Django 5.1.7 on 2025-03-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthReport',
        ),
    ]
