# Generated by Django 5.1.7 on 2025-03-16 07:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_delete_healthreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskalert',
            name='risk_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.riskassessmentresult'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.riskassessmentresult'),
        ),
        migrations.CreateModel(
            name='HealthReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10)),
                ('risk_probability', models.FloatField(default=0)),
                ('blood_pressure', models.IntegerField(default=0)),
                ('cholesterol_level', models.FloatField(default=180)),
                ('glucose_level', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=25)),
                ('recommendations', models.TextField(default='')),
                ('explanation', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RiskAssessment',
        ),
    ]
